// AUTO-GENERATED by scripts/build_imm_conditions.ts — do not edit by hand.
// Source: research/imm_sources/architecture/K15_keenan_2015_imm_probabilistic_simulation.md (appendix table).
// Re-run: `npx tsx scripts/build_imm_conditions.ts`.

import type { IMMCondition } from "./types";

export const IMM_CONDITIONS: IMMCondition[] = [
  {
    "id": "abdominal-injury",
    "label": "Abdominal Injury",
    "family": "traumatic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.conscientiousness"
    ]
  },
  {
    "id": "abdominal-wall-hernia",
    "label": "Abdominal Wall Hernia",
    "family": "GI",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "abnormal-uterine-bleeding",
    "label": "Abnormal Uterine Bleeding",
    "family": "GU",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": []
  },
  {
    "id": "acute-arthritis",
    "label": "Acute Arthritis",
    "family": "musculoskeletal",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "acute-cholecystitis-biliary-colic",
    "label": "Acute Cholecystitis/Biliary Colic",
    "family": "GI",
    "incidenceSource": "astronaut-pre-postflight",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": []
  },
  {
    "id": "acute-compartment-syndrome",
    "label": "Acute Compartment Syndrome",
    "family": "musculoskeletal",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "acute-diverticulitis",
    "label": "Acute Diverticulitis",
    "family": "GI",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "acute-glaucoma",
    "label": "Acute Glaucoma",
    "family": "ophthalmologic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": []
  },
  {
    "id": "acute-pancreatitis",
    "label": "Acute Pancreatitis",
    "family": "GI",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "acute-prostatitis",
    "label": "Acute Prostatitis",
    "family": "GU",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": []
  },
  {
    "id": "acute-radiation-syndrome",
    "label": "Acute Radiation Syndrome",
    "family": "toxicologic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "SPE-coupled",
    "riskFactors": [
      "SPE"
    ],
    "vulnerabilityCriteria": [
      "psych.conscientiousness"
    ]
  },
  {
    "id": "acute-sinusitis",
    "label": "Acute Sinusitis",
    "family": "ENT",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "allergic-reaction-mild-to-moderate",
    "label": "Allergic Reaction (mild to moderate)",
    "family": "infectious",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "altitude-sickness",
    "label": "Altitude Sickness",
    "family": "neurologic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "cognitive.nasa_cognition_battery",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "anaphylaxis",
    "label": "Anaphylaxis",
    "family": "infectious",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "angina-myocardial-infarction",
    "label": "Angina/Myocardial Infarction",
    "family": "cardiovascular",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "ankle-sprain-strain",
    "label": "Ankle Sprain/Strain",
    "family": "musculoskeletal",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "anxiety",
    "label": "Anxiety",
    "family": "psychiatric",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "psych.mmpi2rf_eid",
      "psych.emotional_stability",
      "psych.bdi2_baseline"
    ]
  },
  {
    "id": "appendicitis",
    "label": "Appendicitis",
    "family": "GI",
    "incidenceSource": "astronaut-pre-postflight",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "atrial-fibrillation-atrial-flutter",
    "label": "Atrial Fibrillation/ Atrial Flutter",
    "family": "cardiovascular",
    "incidenceSource": "astronaut-pre-postflight",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "back-injury",
    "label": "Back Injury",
    "family": "musculoskeletal",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "back-pain-space-adaptation",
    "label": "Back Pain (Space Adaptation)",
    "family": "space-adaptation",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "space-adaptation-once",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "barotrauma-ear-sinus-block",
    "label": "Barotrauma (ear/sinus block)",
    "family": "ENT",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "behavioral-emergency",
    "label": "Behavioral Emergency",
    "family": "behavioral",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "behavioral.teamwork",
      "psych.conscientiousness"
    ]
  },
  {
    "id": "burns-secondary-to-fire",
    "label": "Burns secondary to Fire",
    "family": "dermatologic",
    "incidenceSource": "external-model",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "cardiogenic-shock-secondary-to-myocardial-infarction",
    "label": "Cardiogenic Shock secondary to Myocardial Infarction",
    "family": "cardiovascular",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "chest-injury",
    "label": "Chest Injury",
    "family": "traumatic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.conscientiousness"
    ]
  },
  {
    "id": "choking-obstructed-airway",
    "label": "Choking/Obstructed Airway",
    "family": "respiratory",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "constipation-space-adaptation",
    "label": "Constipation (space adaptation)",
    "family": "space-adaptation",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "space-adaptation-once",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "decompression-sickness-secondary-to-extravehicular-activity",
    "label": "Decompression Sickness Secondary to Extravehicular Activity",
    "family": "musculoskeletal",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Beta",
    "processType": "EVA-coupled",
    "riskFactors": [
      "EVA"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "dental-exposed-pulp",
    "label": "Dental : Exposed Pulp",
    "family": "dental",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "dental-caries",
    "label": "Dental Caries",
    "family": "dental",
    "incidenceSource": "astronaut-pre-postflight",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "dental-abscess",
    "label": "Dental: Abscess",
    "family": "dental",
    "incidenceSource": "astronaut-pre-postflight",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "dental-avulsion-tooth-loss",
    "label": "Dental: Avulsion (Tooth Loss)",
    "family": "dental",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "dental-crown-loss",
    "label": "Dental: Crown Loss",
    "family": "dental",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "crowns"
    ],
    "vulnerabilityCriteria": []
  },
  {
    "id": "dental-filling-loss",
    "label": "Dental: Filling Loss",
    "family": "dental",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "depression",
    "label": "Depression",
    "family": "psychiatric",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "psych.mmpi2rf_eid",
      "psych.emotional_stability",
      "psych.bdi2_baseline"
    ]
  },
  {
    "id": "diarrhea",
    "label": "Diarrhea",
    "family": "GI",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "elbow-dislocation",
    "label": "Elbow Dislocation",
    "family": "musculoskeletal",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "elbow-sprain-strain",
    "label": "Elbow Sprain/Strain",
    "family": "musculoskeletal",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "eye-abrasion-foreign-body",
    "label": "Eye Abrasion (foreign body)",
    "family": "ophthalmologic",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "eye-chemical-burn",
    "label": "Eye Chemical Burn",
    "family": "ophthalmologic",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "eye-corneal-ulcer",
    "label": "Eye Corneal Ulcer",
    "family": "ophthalmologic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "contacts"
    ],
    "vulnerabilityCriteria": []
  },
  {
    "id": "eye-infection",
    "label": "Eye Infection",
    "family": "ophthalmologic",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "eye-penetration-foreign-body",
    "label": "Eye Penetration (foreign body)",
    "family": "ophthalmologic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "finger-dislocation",
    "label": "Finger Dislocation",
    "family": "musculoskeletal",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "fingernail-delamination",
    "label": "Fingernail Delamination",
    "family": "musculoskeletal",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "EVA-coupled",
    "riskFactors": [
      "EVA"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "gastroenteritis",
    "label": "Gastroenteritis",
    "family": "GI",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "head-injury",
    "label": "Head Injury",
    "family": "traumatic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.conscientiousness"
    ]
  },
  {
    "id": "headache-co2-induced",
    "label": "Headache (CO2 induced)",
    "family": "neurologic",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "cognitive.nasa_cognition_battery",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "headache-late",
    "label": "Headache (Late)",
    "family": "neurologic",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "cognitive.nasa_cognition_battery",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "headache-space-adaptation",
    "label": "Headache (space adaptation)",
    "family": "space-adaptation",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "space-adaptation-once",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "hearing-loss",
    "label": "Hearing Loss",
    "family": "ENT",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "hemorrhoids",
    "label": "Hemorrhoids",
    "family": "GI",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "herpes-zoster-reactivation-shingles",
    "label": "Herpes Zoster Reactivation (shingles)",
    "family": "infectious",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "hip-sprain-strain",
    "label": "Hip Sprain/Strain",
    "family": "musculoskeletal",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "hip-proximal-femur-fracture",
    "label": "Hip/Proximal Femur Fracture",
    "family": "musculoskeletal",
    "incidenceSource": "external-model",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "hypertension",
    "label": "Hypertension",
    "family": "cardiovascular",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "indigestion",
    "label": "Indigestion",
    "family": "GI",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "influenza",
    "label": "Influenza",
    "family": "infectious",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "insomnia-space-adaptation",
    "label": "Insomnia (space adaptation)",
    "family": "space-adaptation",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "space-adaptation-once",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "interpersonal-conflict",
    "label": "Interpersonal Conflict",
    "family": "behavioral",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "psych.emotional_stability",
      "behavioral.teamwork",
      "psych.conscientiousness"
    ]
  },
  {
    "id": "knee-sprain-strain",
    "label": "Knee Sprain/Strain",
    "family": "musculoskeletal",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "late-insomnia",
    "label": "Late Insomnia",
    "family": "psychiatric",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "psych.mmpi2rf_eid",
      "psych.emotional_stability",
      "psych.bdi2_baseline"
    ]
  },
  {
    "id": "lower-extremity-le-stress-fracture",
    "label": "Lower Extremity (LE) Stress Fracture",
    "family": "musculoskeletal",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "lumbar-spine-fracture",
    "label": "Lumbar Spine Fracture",
    "family": "musculoskeletal",
    "incidenceSource": "external-model",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "medication-overdose-adverse-reaction",
    "label": "Medication Overdose/Adverse Reaction",
    "family": "toxicologic",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "psych.conscientiousness"
    ]
  },
  {
    "id": "mouth-ulcer",
    "label": "Mouth Ulcer",
    "family": "ENT",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "nasal-congestion-space-adaptation",
    "label": "Nasal Congestion (space adaptation)",
    "family": "space-adaptation",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "space-adaptation-once",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "neck-injury",
    "label": "Neck Injury",
    "family": "musculoskeletal",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "nephrolithiasis",
    "label": "Nephrolithiasis",
    "family": "renal",
    "incidenceSource": "astronaut-pre-postflight",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "neurogenic-shock",
    "label": "Neurogenic Shock",
    "family": "neurologic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "cognitive.nasa_cognition_battery",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "nose-bleed-space-adaptation",
    "label": "Nose bleed (space adaptation)",
    "family": "space-adaptation",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "space-adaptation-once",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "otitis-externa",
    "label": "Otitis Externa",
    "family": "ENT",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "otitis-media",
    "label": "Otitis Media",
    "family": "ENT",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "paresthesias",
    "label": "Paresthesias",
    "family": "neurologic",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "EVA-coupled",
    "riskFactors": [
      "EVA"
    ],
    "vulnerabilityCriteria": [
      "cognitive.nasa_cognition_battery",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "pharyngitis",
    "label": "Pharyngitis",
    "family": "ENT",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "respiratory-infection",
    "label": "Respiratory Infection",
    "family": "infectious",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "retinal-detachment",
    "label": "Retinal Detachment",
    "family": "ophthalmologic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": []
  },
  {
    "id": "seizures",
    "label": "Seizures",
    "family": "neurologic",
    "incidenceSource": "astronaut-pre-postflight",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "cognitive.nasa_cognition_battery",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "sepsis",
    "label": "Sepsis",
    "family": "infectious",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "shoulder-dislocation",
    "label": "Shoulder Dislocation",
    "family": "musculoskeletal",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "shoulder-sprain-strain",
    "label": "Shoulder Sprain/Strain",
    "family": "musculoskeletal",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "skin-abrasion",
    "label": "Skin Abrasion",
    "family": "dermatologic",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "skin-infection",
    "label": "Skin Infection",
    "family": "infectious",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "skin-laceration",
    "label": "Skin Laceration",
    "family": "dermatologic",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "skin-rash",
    "label": "Skin Rash",
    "family": "dermatologic",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": []
  },
  {
    "id": "small-bowel-obstruction",
    "label": "Small Bowel Obstruction",
    "family": "GI",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "abdominal-surgery-history"
    ],
    "vulnerabilityCriteria": []
  },
  {
    "id": "smoke-inhalation",
    "label": "Smoke Inhalation",
    "family": "respiratory",
    "incidenceSource": "external-model",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "space-motion-sickness-space-adaptation",
    "label": "Space Motion Sickness (space adaptation)",
    "family": "space-adaptation",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "space-adaptation-once",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "stroke-cerebrovascular-accident",
    "label": "Stroke (cerebrovascular accident)",
    "family": "neurologic",
    "incidenceSource": "astronaut-pre-postflight",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "cognitive.nasa_cognition_battery",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "sudden-cardiac-arrest",
    "label": "Sudden Cardiac Arrest",
    "family": "cardiovascular",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [
      "CAC-positive"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "toxic-exposure-ammonia",
    "label": "Toxic Exposure: Ammonia",
    "family": "toxicologic",
    "incidenceSource": "external-model",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "psych.conscientiousness"
    ]
  },
  {
    "id": "traumatic-hypovolemic-shock",
    "label": "Traumatic Hypovolemic Shock",
    "family": "traumatic",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Fixed",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.conscientiousness"
    ]
  },
  {
    "id": "urinary-incontinence-space-adaptation",
    "label": "Urinary Incontinence (space adaptation)",
    "family": "space-adaptation",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "space-adaptation-once",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "urinary-retention-space-adaptation",
    "label": "Urinary Retention (space adaptation)",
    "family": "space-adaptation",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "space-adaptation-once",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "urinary-tract-infection",
    "label": "Urinary Tract Infection",
    "family": "GU",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": []
  },
  {
    "id": "vaginal-yeast-infection",
    "label": "Vaginal Yeast Infection",
    "family": "GU",
    "incidenceSource": "terrestrial",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [
      "sex-male",
      "sex-female"
    ],
    "vulnerabilityCriteria": []
  },
  {
    "id": "visual-impairment-and-intracranial-pressure-viip-space-adaptation",
    "label": "Visual Impairment and Intracranial Pressure (VIIP)(space adaptation)",
    "family": "space-adaptation",
    "incidenceSource": "in-flight",
    "incidenceDist": "Beta",
    "processType": "SA-VIIP-late",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max",
      "psych.emotional_stability"
    ]
  },
  {
    "id": "wrist-fracture",
    "label": "Wrist Fracture",
    "family": "musculoskeletal",
    "incidenceSource": "external-model",
    "incidenceDist": "Lognormal",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  },
  {
    "id": "wrist-sprain-strain",
    "label": "Wrist Sprain/Strain",
    "family": "musculoskeletal",
    "incidenceSource": "in-flight",
    "incidenceDist": "Gamma",
    "processType": "general-Poisson",
    "riskFactors": [],
    "vulnerabilityCriteria": [
      "physical.vo2max"
    ]
  }
];
