// src/imm/provenance.ts
//
// F3/F4: full simulation-assumption provenance for saved IMM sessions and
// exports. A saved result is only meaningful against the assumptions that
// generated it, so every session/export carries: the operative scenario
// controls (couplingMode, familyBetaScale, chiStar, aggregator), the catalog
// identity, content hashes of the prior set and the active kind-multiplier
// block, the software version, and a snapshot of the evidence-ledger status.
//
// The evidence snapshot also feeds F4: outcome cards and exports state the
// operative fact that accepted parameter coverage is currently 0/4,849 and
// that Monte Carlo intervals describe simulated variability, not empirical
// calibration.

import evidenceStatusJson from "@/data/evidence-status.json";
import { loadIMMPriors } from "./priors";
import {
  PROFILE_EFFECTS,
  PROFILE_MAPPING_VERSION,
  type ProfileEffectEvidenceStatus,
  type ProfileEffectMode,
} from "./profile-effects";
import type { IMMSession } from "./types";
import { SELECTRON_SOURCE_COMMIT, SELECTRON_VERSION } from "../version";

/** Shape of the committed frontend evidence-status snapshot. */
export type EvidenceStatusSnapshot = {
  status: "adjudicated" | "unadjudicated";
  releasePriorsAdjudicated: boolean;
  acceptedCount: number;
  proposalCount: number;
  proposalRefCount: number;
  proposalRefConditionIds: string[];
  activeParameterCount: number;
  acceptedCoveredParameterCount: number;
  uncoveredParameterCount: number;
  malformedAcceptedRowCount: number;
  message: string;
  generatedAt: string;
};

/** The committed evidence-ledger status snapshot (regenerated by
 *  `npm run evidence:status -- --write`). Frozen at session-save time so a
 *  reloaded session reports the coverage that was operative when it ran. */
export const EVIDENCE_STATUS_SNAPSHOT: EvidenceStatusSnapshot =
  evidenceStatusJson as EvidenceStatusSnapshot;

/** One-line operative-coverage statement attached to every outcome surface. */
export const EVIDENCE_COVERAGE_STATEMENT =
  `Scenario output under unadjudicated priors. Accepted evidence coverage: ` +
  `${EVIDENCE_STATUS_SNAPSHOT.acceptedCoveredParameterCount} / ` +
  `${EVIDENCE_STATUS_SNAPSHOT.activeParameterCount} parameter paths. ` +
  `Monte Carlo intervals describe simulated mission variability and do not ` +
  `establish empirical calibration.`;

export type ActiveProfileEffectSnapshot = {
  profilePath: string;
  estimate: number;
  evidenceStatus: ProfileEffectEvidenceStatus;
};

export type SavedOutcomeStatus =
  | "current"
  | "stale-priors"
  | "stale-profile-effects"
  | "stale-software";

function profileEffectApplies(
  evidenceStatus: ProfileEffectEvidenceStatus,
  mode: ProfileEffectMode,
): boolean {
  if (mode === "off") return false;
  if (mode === "exploratory") return evidenceStatus !== "unsupported";
  return evidenceStatus === "accepted";
}

/**
 * SHA-256 hex digest of a UTF-8 string via WebCrypto SubtleCrypto. Falls back
 * to a deterministic non-crypto marker only if SubtleCrypto is unavailable
 * (e.g. a constrained non-browser host), so the save path never throws.
 */
export async function sha256Hex(input: string): Promise<string> {
  const subtle = globalThis.crypto?.subtle;
  if (!subtle) {
    return `unavailable:${input.length}`;
  }
  const data = new TextEncoder().encode(input);
  const digest = await subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Stable SHA-256 over the canonical JSON of the loaded prior set. Detects
 * whether `imm-priors.json` changed between session save and reload.
 */
export async function computePriorsHash(): Promise<string> {
  const canonical = JSON.stringify(loadIMMPriors());
  return sha256Hex(canonical);
}

/**
 * Stable SHA-256 over the active `global_calibration.kind_multipliers` block.
 * Detects whether the per-(mission-kind, condition) multiplier map changed
 * between session save and reload.
 */
export async function computeKindMultiplierHash(): Promise<string> {
  const priors = loadIMMPriors();
  const block = priors.global_calibration?.kind_multipliers ?? {};
  return sha256Hex(JSON.stringify(block));
}

/** Stable SHA-256 over the complete PROFILE_EFFECTS registry. */
export async function computeProfileEffectsHash(): Promise<string> {
  return sha256Hex(JSON.stringify(PROFILE_EFFECTS));
}

/** Active numeric effects under a specific operator profile-effect mode. */
export function activeProfileEffectsForMode(
  mode: ProfileEffectMode = "adjudicated",
): ActiveProfileEffectSnapshot[] {
  return PROFILE_EFFECTS
    .filter((effect) =>
      typeof effect.estimate === "number" &&
      Number.isFinite(effect.estimate) &&
      profileEffectApplies(effect.evidenceStatus, mode),
    )
    .map((effect) => ({
      profilePath: effect.profilePath,
      estimate: effect.estimate as number,
      evidenceStatus: effect.evidenceStatus,
    }));
}

/**
 * Compare a saved session's assumptions against the currently loaded engine.
 * Missing legacy provenance is stale by design: old rows are still loadable,
 * but their saved outcomes are not presented as current-engine results.
 */
export async function classifySavedOutcomeStatus(
  session: Pick<
    IMMSession,
    | "priorsHash"
    | "kindMultiplierHash"
    | "profileMappingVersion"
    | "profileEffectsHash"
    | "softwareVersion"
    | "sourceCommit"
  >,
): Promise<SavedOutcomeStatus> {
  const [currentPriorsHash, currentKindMultiplierHash, currentProfileEffectsHash] =
    await Promise.all([
      computePriorsHash(),
      computeKindMultiplierHash(),
      computeProfileEffectsHash(),
    ]);

  if (
    session.softwareVersion !== SELECTRON_VERSION ||
    session.sourceCommit !== SELECTRON_SOURCE_COMMIT
  ) {
    return "stale-software";
  }
  if (
    session.profileMappingVersion !== PROFILE_MAPPING_VERSION ||
    session.profileEffectsHash !== currentProfileEffectsHash
  ) {
    return "stale-profile-effects";
  }
  if (
    session.priorsHash !== currentPriorsHash ||
    session.kindMultiplierHash !== currentKindMultiplierHash
  ) {
    return "stale-priors";
  }
  return "current";
}

export { PROFILE_MAPPING_VERSION };
