// src/imm/provenance.ts
//
// F3/F4: full simulation-assumption provenance for saved IMM sessions and
// exports. A saved result is only meaningful against the assumptions that
// generated it, so every session/export carries: the operative scenario
// controls (couplingMode, familyBetaScale, chiStar, aggregator), the catalog
// identity, content hashes of the prior set and the active kind-multiplier
// block, the software version, and a snapshot of the evidence-ledger status.
//
// The evidence snapshot also feeds F4: outcome cards and exports state the
// operative fact that accepted parameter coverage is currently 0/4,846 and
// that Monte Carlo intervals describe simulated variability, not empirical
// calibration.

import evidenceStatusJson from "@/data/evidence-status.json";
import { loadIMMPriors } from "./priors";

/** Shape of the committed frontend evidence-status snapshot. */
export type EvidenceStatusSnapshot = {
  status: "adjudicated" | "unadjudicated";
  releasePriorsAdjudicated: boolean;
  acceptedCount: number;
  proposalCount: number;
  proposalRefCount: number;
  proposalRefConditionIds: string[];
  activeParameterCount: number;
  acceptedCoveredParameterCount: number;
  uncoveredParameterCount: number;
  malformedAcceptedRowCount: number;
  message: string;
  generatedAt: string;
};

/** The committed evidence-ledger status snapshot (regenerated by
 *  `npm run evidence:status -- --write`). Frozen at session-save time so a
 *  reloaded session reports the coverage that was operative when it ran. */
export const EVIDENCE_STATUS_SNAPSHOT: EvidenceStatusSnapshot =
  evidenceStatusJson as EvidenceStatusSnapshot;

/** One-line operative-coverage statement attached to every outcome surface. */
export const EVIDENCE_COVERAGE_STATEMENT =
  `Scenario output under unadjudicated priors. Accepted evidence coverage: ` +
  `${EVIDENCE_STATUS_SNAPSHOT.acceptedCoveredParameterCount} / ` +
  `${EVIDENCE_STATUS_SNAPSHOT.activeParameterCount} parameter paths. ` +
  `Monte Carlo intervals describe simulated mission variability and do not ` +
  `establish empirical calibration.`;

/**
 * SHA-256 hex digest of a UTF-8 string via WebCrypto SubtleCrypto. Falls back
 * to a deterministic non-crypto marker only if SubtleCrypto is unavailable
 * (e.g. a constrained non-browser host), so the save path never throws.
 */
export async function sha256Hex(input: string): Promise<string> {
  const subtle = globalThis.crypto?.subtle;
  if (!subtle) {
    return `unavailable:${input.length}`;
  }
  const data = new TextEncoder().encode(input);
  const digest = await subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Stable SHA-256 over the canonical JSON of the loaded prior set. Detects
 * whether `imm-priors.json` changed between session save and reload.
 */
export async function computePriorsHash(): Promise<string> {
  const canonical = JSON.stringify(loadIMMPriors());
  return sha256Hex(canonical);
}

/**
 * Stable SHA-256 over the active `global_calibration.kind_multipliers` block.
 * Detects whether the per-(mission-kind, condition) multiplier map changed
 * between session save and reload.
 */
export async function computeKindMultiplierHash(): Promise<string> {
  const priors = loadIMMPriors();
  const block = priors.global_calibration?.kind_multipliers ?? {};
  return sha256Hex(JSON.stringify(block));
}